In [1]:
import pandas as pd
import numpy as np

# Fraudalent Shops Dataset

In [4]:
shop_df = pd.read_csv("C:/Users/harry/OneDrive/Desktop/NUS Modules/DSA4263_project/DSA4263/data/Fraudulent_online_shops_dataset.csv")

In [5]:
shop_df.head()

,Online shop URL,Label,Domain length,Top domain length,Presence of prefix 'www',Number of digits,Number of letters,Number of dots (.),Number of hyphens (-),Presence of credit card payment,...,SSL certificate expire date,Issuer organization,SSL certificate issuer organization list item,Indication of young domain,Domain registration date,Presence of TrustPilot reviews,TrustPilot score,Presence of SiteJabber reviews,Presence in the standard Tranco list,Tranco List rank
0,https://www.allaccessorybest.com,fraudulent,24,3,1,0,27,2,0,1,...,Oct 11 03:53:36 2023 GMT,Google Trust Services LLC,9,1,2023-05-15 03:35,0,NaN,0,0,-1
1,https://www.b-watches.shop,fraudulent,18,4,1,0,20,2,1,0,...,Jun 16 23:59:59 2024 GMT,"Cloudflare, Inc.",1,1,2023-06-18 05:43,0,NaN,0,0,-1
2,https://www.waeschenamen-windrath.de,legitimate,28,2,1,0,30,2,1,1,...,Oct 24 21:53:20 2023 GMT,Let's Encrypt,2,2,Hidden,0,-1.0,0,0,-1
3,https://vendoprint.se,legitimate,13,2,0,0,17,1,0,1,...,Oct 9 15:13:00 2023 GMT,Google Trust Services LLC,9,1,2022-09-20 00:00,0,-1.0,0,0,-1
4,https://www.newbikeland.com,fraudulent,19,3,1,0,22,2,0,1,...,Oct 25 08:20:27 2023 GMT,Let's Encrypt,2,1,2023-07-27 09:05,0,NaN,0,0,-1

In [6]:
shop_df.describe()

,Domain length,Top domain length,Presence of prefix 'www',Number of digits,Number of letters,Number of dots (.),Number of hyphens (-),Presence of credit card payment,Presence of money back payment,Presence of cash on delivery payment,Presence of crypto currency,Presence of free contact emails,Presence of logo URL,SSL certificate issuer organization list item,Indication of young domain,Presence of TrustPilot reviews,TrustPilot score,Presence of SiteJabber reviews,Presence in the standard Tranco list,Tranco List rank
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.00000,1140.000000,1140.000000,1140.000000,580.000000,1140.000000,1140.000000,1140.000000
mean,18.341228,2.851754,0.665789,0.070175,21.654386,1.708772,0.157895,0.763158,0.713158,0.238596,0.035088,1.053509,0.82193,4.570175,0.620175,0.223684,1.014828,0.038596,0.015789,9710.771053
std,4.512033,0.741322,0.471921,0.395748,4.307723,0.495203,0.403648,0.425331,0.452486,0.426413,0.184082,1.114095,0.38274,3.336470,0.664235,0.416896,2.363742,0.192716,0.124715,84946.859868
min,7.000000,2.000000,0.000000,0.000000,11.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000
25%,15.000000,2.000000,0.000000,0.000000,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.00000,2.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000
50%,19.000000,3.000000,1.000000,0.000000,22.000000,2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.00000,2.000000,1.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000
75%,21.000000,3.000000,1.000000,0.000000,24.250000,2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.00000,9.000000,1.000000,0.000000,3.600000,0.000000,0.000000,-1.000000
max,38.000000,13.000000,1.000000,4.000000,39.000000,3.000000,4.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.00000,11.000000,2.000000,1.000000,5.000000,1.000000,1.000000,964101.000000

# Transaction Dataset

In [7]:
trans_df = pd.read_csv("C:/Users/harry/OneDrive/Desktop/NUS Modules/DSA4263_project/DSA4263/data/transaction_data_100K_full.csv")

In [8]:
trans_df.head()

,EVENT_LABEL,EVENT_TIMESTAMP,LABEL_TIMESTAMP,EVENT_ID,ENTITY_TYPE,ENTITY_ID,card_bin,customer_name,billing_street,billing_city,...,billing_country,customer_job,ip_address,customer_email,billing_phone,user_agent,product_category,order_price,payment_currency,merchant
0,0,2023-02-14T02:27:41Z,2023-02-14T02:27:41Z,100005a527cbcd5de0c4c878288912017,customer,634-80-3034,259703,Ricky,8247 Christopher Mountains Apt. 462,Paint Lick,...,US,IT sales professional,120.79.45.214,woodardbrenda@gmail.com,786-385-2594,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,grocery_net,95.77,ARS,fraud_Runolfsson and Sons
1,0,2023-01-13T01:30:22Z,2023-01-13T01:30:22Z,1000091e85eb1cd32ec4b8afcf818fea5,customer,815-02-7980,380256,Kimberly,945 Lowe Vista,Providence,...,US,Aeronautical engineer,212.42.56.229,scottdalton@robinson.biz,266-305-0756-3308,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_4 ...,kids_pets,21.88,BND,fraud_Larkin Ltd
2,0,2023-02-20T04:12:39Z,2023-02-20T04:12:39Z,10000a7862d0ca68257a20149111ec1b4,customer,287-97-0013,471448,Ronald,11307 Munoz Mission Suite 083,Arlington,...,US,Ambulance person,164.238.228.201,pjohnson@cruz.info,+1-068-919-8279,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_4 like...,shopping_pos,9.62,NAD,fraud_Metz-Boehm
3,0,2022-12-13T09:06:33Z,2022-12-13T09:06:33Z,1000130fddbb2383646840294dcb7f6fa,customer,819-30-8170,343617,Jessica,90815 Brandon Junctions,San Diego,...,US,"Nurse, mental health",210.108.230.215,progers@hansen-yu.com,+1-115-473-9557,Mozilla/5.0 (compatible; MSIE 6.0; Windows CE;...,home,36.96,LTL,fraud_Quitzon-Goyette
4,0,2023-03-04T09:48:57Z,2023-03-04T09:48:57Z,1000230990f537b8e89786821a3abf10e,customer,285-06-1069,353899,Robert,63165 Natasha Extensions,Mayfield,...,US,Teaching laboratory technician,189.103.115.129,reevesmichael@gmail.com,+1-057-636-3058,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_11_...,shopping_pos,2.08,GIP,fraud_Turner and Sons

# Registration Dataset

In [9]:
register_df = pd.read_csv("C:/Users/harry/OneDrive/Desktop/NUS Modules/DSA4263_project/DSA4263/data/registration_data_20K_full.csv")

In [10]:
register_df.head()

,ip_address,email_address,billing_state,user_agent,billing_postal,phone_number,EVENT_TIMESTAMP,billing_address,EVENT_LABEL
0,112.136.132.151,fake_cgonzales@example.net,NC,Mozilla/5.0 (iPad; CPU iPad OS 10_3_3 like Mac...,34491,(555)333 - 9246,2022-10-14T00:28:30Z,12351 Amanda Knolls Fake St.,legit
1,192.169.234.143,fake_dustin64@example.net,CO,Mozilla/5.0 (Windows; U; Windows NT 6.1) Apple...,34555,(555)779 - 5604,2022-11-29T22:19:40Z,691 Deborah Estate Fake St.,legit
2,185.112.224.79,fake_samuel59@example.net,CO,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,33611,(555)948 - 9198,2023-02-18T09:16:19Z,28583 Joseph Tunnel Fake St.,legit
3,68.73.183.186,fake_tinalopez@example.net,TN,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,33520,(555)477 - 7885,2022-12-19T09:13:35Z,019 Linda Via Fake St.,legit
4,117.65.246.206,fake_alyssa53@example.com,NM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,33889,(555)873 - 2599,2023-01-28T15:32:34Z,1023 Cook Loaf Fake St.,legit