In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
# from imblearn.over_sampling import SMOTE
from datetime import datetime
from urllib.parse import urlparse

# Fraudalent Shops Dataset

In [4]:
shop_df = pd.read_csv("C:/Users/harry/OneDrive/Desktop/NUS Modules/DSA4263_project/DSA4263/data/Fraudulent_online_shops_dataset.csv")

In [5]:
shop_df.head()

,Online shop URL,Label,Domain length,Top domain length,Presence of prefix 'www',Number of digits,Number of letters,Number of dots (.),Number of hyphens (-),Presence of credit card payment,...,SSL certificate expire date,Issuer organization,SSL certificate issuer organization list item,Indication of young domain,Domain registration date,Presence of TrustPilot reviews,TrustPilot score,Presence of SiteJabber reviews,Presence in the standard Tranco list,Tranco List rank
0,https://www.allaccessorybest.com,fraudulent,24,3,1,0,27,2,0,1,...,Oct 11 03:53:36 2023 GMT,Google Trust Services LLC,9,1,2023-05-15 03:35,0,NaN,0,0,-1
1,https://www.b-watches.shop,fraudulent,18,4,1,0,20,2,1,0,...,Jun 16 23:59:59 2024 GMT,"Cloudflare, Inc.",1,1,2023-06-18 05:43,0,NaN,0,0,-1
2,https://www.waeschenamen-windrath.de,legitimate,28,2,1,0,30,2,1,1,...,Oct 24 21:53:20 2023 GMT,Let's Encrypt,2,2,Hidden,0,-1.0,0,0,-1
3,https://vendoprint.se,legitimate,13,2,0,0,17,1,0,1,...,Oct 9 15:13:00 2023 GMT,Google Trust Services LLC,9,1,2022-09-20 00:00,0,-1.0,0,0,-1
4,https://www.newbikeland.com,fraudulent,19,3,1,0,22,2,0,1,...,Oct 25 08:20:27 2023 GMT,Let's Encrypt,2,1,2023-07-27 09:05,0,NaN,0,0,-1

In [6]:
shop_df.describe()

,Domain length,Top domain length,Presence of prefix 'www',Number of digits,Number of letters,Number of dots (.),Number of hyphens (-),Presence of credit card payment,Presence of money back payment,Presence of cash on delivery payment,Presence of crypto currency,Presence of free contact emails,Presence of logo URL,SSL certificate issuer organization list item,Indication of young domain,Presence of TrustPilot reviews,TrustPilot score,Presence of SiteJabber reviews,Presence in the standard Tranco list,Tranco List rank
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.00000,1140.000000,1140.000000,1140.000000,580.000000,1140.000000,1140.000000,1140.000000
mean,18.341228,2.851754,0.665789,0.070175,21.654386,1.708772,0.157895,0.763158,0.713158,0.238596,0.035088,1.053509,0.82193,4.570175,0.620175,0.223684,1.014828,0.038596,0.015789,9710.771053
std,4.512033,0.741322,0.471921,0.395748,4.307723,0.495203,0.403648,0.425331,0.452486,0.426413,0.184082,1.114095,0.38274,3.336470,0.664235,0.416896,2.363742,0.192716,0.124715,84946.859868
min,7.000000,2.000000,0.000000,0.000000,11.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000
25%,15.000000,2.000000,0.000000,0.000000,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.00000,2.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000
50%,19.000000,3.000000,1.000000,0.000000,22.000000,2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.00000,2.000000,1.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000
75%,21.000000,3.000000,1.000000,0.000000,24.250000,2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.00000,9.000000,1.000000,0.000000,3.600000,0.000000,0.000000,-1.000000
max,38.000000,13.000000,1.000000,4.000000,39.000000,3.000000,4.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.00000,11.000000,2.000000,1.000000,5.000000,1.000000,1.000000,964101.000000

# Transaction Dataset

In [7]:
trans_df = pd.read_csv("C:/Users/harry/OneDrive/Desktop/NUS Modules/DSA4263_project/DSA4263/data/transaction_data_100K_full.csv")

In [8]:
trans_df.head()

,EVENT_LABEL,EVENT_TIMESTAMP,LABEL_TIMESTAMP,EVENT_ID,ENTITY_TYPE,ENTITY_ID,card_bin,customer_name,billing_street,billing_city,...,billing_country,customer_job,ip_address,customer_email,billing_phone,user_agent,product_category,order_price,payment_currency,merchant
0,0,2023-02-14T02:27:41Z,2023-02-14T02:27:41Z,100005a527cbcd5de0c4c878288912017,customer,634-80-3034,259703,Ricky,8247 Christopher Mountains Apt. 462,Paint Lick,...,US,IT sales professional,120.79.45.214,woodardbrenda@gmail.com,786-385-2594,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,grocery_net,95.77,ARS,fraud_Runolfsson and Sons
1,0,2023-01-13T01:30:22Z,2023-01-13T01:30:22Z,1000091e85eb1cd32ec4b8afcf818fea5,customer,815-02-7980,380256,Kimberly,945 Lowe Vista,Providence,...,US,Aeronautical engineer,212.42.56.229,scottdalton@robinson.biz,266-305-0756-3308,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_4 ...,kids_pets,21.88,BND,fraud_Larkin Ltd
2,0,2023-02-20T04:12:39Z,2023-02-20T04:12:39Z,10000a7862d0ca68257a20149111ec1b4,customer,287-97-0013,471448,Ronald,11307 Munoz Mission Suite 083,Arlington,...,US,Ambulance person,164.238.228.201,pjohnson@cruz.info,+1-068-919-8279,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_4 like...,shopping_pos,9.62,NAD,fraud_Metz-Boehm
3,0,2022-12-13T09:06:33Z,2022-12-13T09:06:33Z,1000130fddbb2383646840294dcb7f6fa,customer,819-30-8170,343617,Jessica,90815 Brandon Junctions,San Diego,...,US,"Nurse, mental health",210.108.230.215,progers@hansen-yu.com,+1-115-473-9557,Mozilla/5.0 (compatible; MSIE 6.0; Windows CE;...,home,36.96,LTL,fraud_Quitzon-Goyette
4,0,2023-03-04T09:48:57Z,2023-03-04T09:48:57Z,1000230990f537b8e89786821a3abf10e,customer,285-06-1069,353899,Robert,63165 Natasha Extensions,Mayfield,...,US,Teaching laboratory technician,189.103.115.129,reevesmichael@gmail.com,+1-057-636-3058,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_11_...,shopping_pos,2.08,GIP,fraud_Turner and Sons

In [15]:
trans_df.describe()

,EVENT_LABEL,card_bin,billing_zip,billing_latitude,billing_longitude,order_price
count,116705.000000,116705.000000,116705.000000,116705.000000,116705.000000,116705.000000
mean,0.101975,410012.297999,49718.200386,38.945511,-91.068870,114.683963
std,0.302617,124968.238828,27298.642762,5.190024,15.034839,229.441548
min,0.000000,180000.000000,1001.000000,19.066800,-176.787400,1.000000
25%,0.000000,348663.000000,26627.000000,35.567500,-97.213800,11.730000
50%,0.000000,404827.000000,49749.000000,39.523200,-88.291900,53.220000
75%,0.000000,481111.000000,72017.000000,42.175800,-80.359200,97.000000
max,1.000000,676399.000000,99929.000000,71.234600,-67.040800,22059.750000

## Data preprocessing

### Remove duplicates

In [18]:
print(trans_df.shape)

(116705, 24)

In [57]:
trans_df_final = trans_df.drop_duplicates()

In [32]:
print(trans_df_final.shape)

(116705, 24)

### Convert event_timestamp to datetime

In [66]:
trans_df_final['EVENT_TIMESTAMP'] = pd.to_datetime(trans_df_final['EVENT_TIMESTAMP'])

### Check for missing values

### Convert categorical to numerical

In [58]:
categorical_columns = ['billing_state', 'customer_job', 'product_category', 'payment_currency', 'merchant']
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    trans_df_final[col] = le.fit_transform(trans_df_final[col])
    label_encoders[col] = le

### Extract domain from email

In [59]:
trans_df_final['email_domain'] = trans_df_final['customer_email'].apply(lambda x: urlparse(f"http://{x.split('@')[-1]}").netloc if pd.notnull(x) else 'unknown')

### Extract device type from user agent

In [60]:
trans_df_final['is_mobile'] = trans_df_final['user_agent'].str.contains("Mobile|iPhone|Android", na=False).astype(int)

### Drop PII information and irrelevant columns

In [61]:
trans_df_final.drop(['LABEL_TIMESTAMP','customer_name', 'billing_phone', 'customer_email', 'user_agent', 'ENTITY_TYPE'], axis=1, inplace=True)

In [67]:
trans_df_final

,EVENT_LABEL,EVENT_TIMESTAMP,EVENT_ID,ENTITY_ID,card_bin,billing_street,billing_city,billing_state,billing_zip,billing_latitude,billing_longitude,billing_country,customer_job,ip_address,product_category,order_price,payment_currency,merchant,email_domain,is_mobile
0,0,2023-02-14 02:27:41+00:00,100005a527cbcd5de0c4c878288912017,634-80-3034,259703,8247 Christopher Mountains Apt. 462,Paint Lick,17,40461,37.6092,-84.4269,US,309,120.79.45.214,3,95.77,6,539,gmail.com,0
1,0,2023-01-13 01:30:22+00:00,1000091e85eb1cd32ec4b8afcf818fea5,815-02-7980,380256,945 Lowe Vista,Providence,27,27315,36.4873,-79.4041,US,24,212.42.56.229,7,21.88,17,373,robinson.biz,0
2,0,2023-02-20 04:12:39+00:00,10000a7862d0ca68257a20149111ec1b4,287-97-0013,471448,11307 Munoz Mission Suite 083,Arlington,10,39813,31.4420,-84.7241,US,32,164.238.228.201,12,9.62,101,425,cruz.info,1
3,0,2022-12-13 09:06:33+00:00,1000130fddbb2383646840294dcb7f6fa,819-30-8170,343617,90815 Brandon Junctions,San Diego,4,92108,32.7783,-117.1335,US,403,210.108.230.215,6,36.96,85,492,hansen-yu.com,0
4,0,2023-03-04 09:48:57+00:00,1000230990f537b8e89786821a3abf10e,285-06-1069,353899,63165 Natasha Extensions,Mayfield,34,12117,43.1411,-74.2444,US,590,189.103.115.129,12,2.08,50,640,gmail.com,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116700,1,2022-11-24 07:43:43+00:00,1fffe4e48cf55836b733b5dc4b30eb839,593-07-2598,180044,65416 Cole Track,Goose Lake,12,52750,41.9799,-90.3819,US,557,32.125.205.189,0,595.63,95,476,gmail.com,0
116701,0,2023-01-20 07:52:58+00:00,1fffeb32941694b1f0b25016151c609e0,037-89-5070,352609,1495 Jennifer Neck Suite 989,Lansing,49,25862,38.0869,-81.0588,US,326,11.163.2.23,11,1027.12,33,593,gmail.com,0
116702,0,2023-02-07 01:00:00+00:00,1ffff3d968571151016b631bf32b48fa1,178-32-8103,405012,4004 Alexa Stream Apt. 712,Brentwood,42,37027,36.0063,-86.7909,US,457,195.96.153.154,11,1086.40,66,487,richardson.org,1
116703,0,2022-12-29 21:59:00+00:00,1ffff407b1a10026a19c9b4179b0ec6a7,791-41-9826,601154,122 Reynolds Shore,Richardson,43,75080,32.9660,-96.7452,US,37,200.244.199.8,12,600.76,27,483,gmail.com,0
116704,0,2023-02-16 00:09:09+00:00,1ffff98c38ee1b47112b30828f905d037,617-78-7415,498726,76424 Williams Run,Seminole,38,16253,40.8478,-79.4516,US,304,41.46.230.67,8,812.06,48,177,yahoo.com,0

# Registration Dataset

In [9]:
register_df = pd.read_csv("C:/Users/harry/OneDrive/Desktop/NUS Modules/DSA4263_project/DSA4263/data/registration_data_20K_full.csv")

In [10]:
register_df.head()

,ip_address,email_address,billing_state,user_agent,billing_postal,phone_number,EVENT_TIMESTAMP,billing_address,EVENT_LABEL
0,112.136.132.151,fake_cgonzales@example.net,NC,Mozilla/5.0 (iPad; CPU iPad OS 10_3_3 like Mac...,34491,(555)333 - 9246,2022-10-14T00:28:30Z,12351 Amanda Knolls Fake St.,legit
1,192.169.234.143,fake_dustin64@example.net,CO,Mozilla/5.0 (Windows; U; Windows NT 6.1) Apple...,34555,(555)779 - 5604,2022-11-29T22:19:40Z,691 Deborah Estate Fake St.,legit
2,185.112.224.79,fake_samuel59@example.net,CO,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,33611,(555)948 - 9198,2023-02-18T09:16:19Z,28583 Joseph Tunnel Fake St.,legit
3,68.73.183.186,fake_tinalopez@example.net,TN,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,33520,(555)477 - 7885,2022-12-19T09:13:35Z,019 Linda Via Fake St.,legit
4,117.65.246.206,fake_alyssa53@example.com,NM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,33889,(555)873 - 2599,2023-01-28T15:32:34Z,1023 Cook Loaf Fake St.,legit